### ISSUE TITLE
Minimum node.js version missing in readme

### ISSUE THREAD

**Issue by MDylan** [LaravelDaily/Larastarters#103]
Hi,

Today I tried this package, and first it throw error when vite try to install.
After that I checked my node version, and it was too old (v14). 
So minimum node version is (currently) v16 based on [documentation](https://laravel.com/docs/9.x/vite#installing-node)).

**Comment by krekas** [comment]
@MDylan it has nothing to do with this package

**Comment by PovilasKorop** [comment]
@MDylan yes as @krekas said it's requirement from Laravel, not from our package
