### ISSUE TITLE
is windmill using the latest fork?

### ISSUE THREAD

**Issue by SHJordan** [LaravelDaily/Larastarters#107]
Asking because https://github.com/macCesar/windmill-dashboard is actually using tailwind v3 and have been PR approved by estevanmaito/windmill-dashboard

>         Upgraded to version 3 by [macCesar](https://github.com/macCesar/windmill-dashboard)
> 
> _Originally posted by @moalamri in https://github.com/estevanmaito/windmill-dashboard/issues/40#issuecomment-1116666602_
>

**Comment by moalamri** [comment]
@SHJordan indeed it is, I'm not sure if any manual work is done to make it compatible, you could check the commits history to see. Anyways it is running on tailwindcss v3.0.24

**Comment by moalamri** [comment]
https://github.com/macCesar/windmill-dashboard/blob/78170b292c9520d96b37ea84a5fe0417ad04a930/package.json#L26

**Comment by krekas** [comment]
@SHJordan default breeze installation uses tailwind v3.1 and larastarters package doesn't change this version. Everything works. If you have anything to change or improve you are always welcome to make a pr :)

**Comment by PovilasKorop** [comment]
Closing as inactive, with no replies for 2 weeks
