### ISSUE TITLE
Larastarters CoreUI 

### ISSUE THREAD

**Issue by boedyirh** [LaravelDaily/Larastarters#112]
I am trying to install Larastarters CoreUI. It is installed  correctly. But it seems there is problem
![image](https://user-images.githubusercontent.com/10396931/216943043-435426be-ef23-4896-95d3-446bc1b2aab1.png)
Replacing public/js/coreui.bundle.min.js version 4.0.5 
with the original file from https://coreui.io version 4.2.3

solve the problem

**Comment by krekas** [comment]
@boedyirh can you make a PR with the fix?

**Comment by boedyirh** [comment]
OK.

**Comment by krekas** [comment]
@boedyirh wait, for you didn't work sidebar toggle button? Because for me it works just fine.

@PovilasKorop nevertheless we can upgrade it with pr #113

**Comment by boedyirh** [comment]
I am not sure about this, It didn't work in my computer. the burger icon doesnot show and hide side navigation bar. But after upgrade coreui.min.js to the latest version. It works fine.

**Comment by PovilasKorop** [comment]
@boedyirh ok I've merged the PR, thanks for contribution!
