### ISSUE TITLE
Volt Header

### ISSUE THREAD

**Issue by thenibirahmed** [LaravelDaily/Larastarters#118]
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/64247665/219271086-2b7cf2d6-aeb1-452c-b7bb-0f7d5fc21205.png">

Can we have this navigation on volt?

**Comment by krekas** [comment]
You mean the search input?

**Comment by thenibirahmed** [comment]
no the button when it clicked the left sidebar shrinks

**Comment by krekas** [comment]
Can you make pr to add it?

**Comment by PovilasKorop** [comment]
Closing as feature is not in plans at the moment.
