### ISSUE TITLE
[DOC] Laravel 10 Compatibility

### ISSUE THREAD

**Issue by dansysanalyst** [LaravelDaily/Larastarters#120]
Hi Laravel Daily Team,

README says **"Works only with the latest Laravel 9"**, however, Povilas [tweeted](https://twitter.com/PovilasKorop/status/1627606994549985282) about a Laravel 10 update.

<p align="center">
   <img src="https://user-images.githubusercontent.com/79267265/220314606-8f4a74ae-c59e-43ac-8356-6a2606954ca1.png" width="500">
</p>

I also attach a screenshot of the installation wizard with the new output format, if you would like to update it.

![screenshot](https://user-images.githubusercontent.com/79267265/220314313-d3055051-3997-427d-98df-8bc7bbd34dd7.png)

Thanks for the great package!

**Comment by krekas** [comment]
Can you make pr to update readme?
