### ISSUE TITLE
Error: [vite]: Rollup failed to resolve import "lodash"

### ISSUE THREAD

**Issue by 1MuneebUrRehman** [LaravelDaily/Larastarters#124]
While running "php artisan larastarters:install" command and selecting option 2, followed by option 0. During the build, Vite failed to resolve the import "lodash" from "C:/laragon/www/test/resources/js/bootstrap.js".

**Laravel v10.3.2 (PHP v8.1.10)**

### Steps to Reproduce

1. Run composer require laraveldaily/larastarters --dev command in your Laravel project.
2. Run php artisan larastarters:install command.
3. Select option 2, followed by option 0.

### Error Traceback
```
Error: [vite]: Rollup failed to resolve import "lodash" from "C:/laragon/www/test/resources/js/bootstrap.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///C:/laragon/www/test/node_modules/vite/dist/node/chunks/dep-ca21228b.js:44792:19)
    at onwarn (file:///C:/laragon/www/test/node_modules/vite/dist/node/chunks/dep-ca21228b.js:44562:13)
    at Object.onwarn (file:///C:/laragon/www/test/node_modules/rollup/dist/es/shared/node-entry.js:24950:13)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/laragon/www/test/node_modules/rollup/dist/es/shared/node-entry.js:23632:26)
    at file:///C:/laragon/www/test/node_modules/rollup/dist/es/shared/node-entry.js:23592:26
```

![image](https://user-images.githubusercontent.com/58783843/223795075-1238baf8-9623-4ab4-bc6a-4f7306096adf.png)

![image](https://user-images.githubusercontent.com/58783843/223795663-3a25e4e6-4bf9-440f-8d52-ec3c190c803a.png)

### Solution

```
npm install lodash
npm install && npm run dev
```

**Comment by 1MuneebUrRehman** [comment]
@PovilasKorop Can you look into this? Thanks

**Comment by krekas** [comment]
This issue is related to this pr https://github.com/laravel/ui/pull/247 could you make a pr with a fix?

**Comment by 1MuneebUrRehman** [comment]
I would like to help fix this issue. However, I'm not quite familiar with the codebase yet and I'm still learning. Could you please provide me with some guidance on how I can go about fixing this issue? Any pointers or suggestions would be greatly appreciated. Thank you!

**Comment by 1MuneebUrRehman** [comment]
Hi @krekas! 

I've just submitted a pull request to address the issue [#124](https://github.com/LaravelDaily/Larastarters/issues/124) and I was wondering if you could take a look at it and provide me with some feedback. I'd really appreciate it!

The link to the pull request is [here](https://github.com/LaravelDaily/Larastarters/pull/125). Let me know if you have any questions or if there's anything else I can do to help. Thanks a lot for your time!
