### ISSUE TITLE
Two-level menus, when more than one (not sure if this is issue)

### ISSUE THREAD

**Issue by beli0135** [LaravelDaily/Larastarters#127]
It's about two-level menu. Not sure if this is an issue or I am doing something wrong. 
 Default code provided by windmill..
 
```
 <li class="relative px-6 py-3">
                <button  class="inline-flex items-center justify-between w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200"
                         @click="toggleMultiLevelMenu" aria-haspopup="true" id="srchbtn" name="srchbtn">
	....
	 <template x-if="isMultiLevelMenuOpen">
                    <ul x-transition:enter="transition-all ease-in-out duration-300"
	...
```

As I understand, this is controlled in init-alpine.js with

```
isMultiLevelMenuOpen: false,
toggleMultiLevelMenu() {
	this.isMultiLevelMenuOpen = !this.isMultiLevelMenuOpen
},

```	
When I wanted another two level menu, I copied the code in blade, and as expected, when I click on one, both opens.
Then I created another function 

```
isMultiLevelMenuOpenSecond: false,
toggleMultiLevelMenuSecond() {
	this.isMultiLevelMenuOpenSecond = !this.isMultiLevelMenuOpenSecond
},
```

and linked to it, but then, this one is not working. 
What am I missing? Is there another place when I should put the code, as I need those two-level menus to open separately.
Also, is there a config where I can tell one menu start opened?

**Comment by krekas** [comment]
It's just for demo. You should do it yourself. Also, to show as an open set isMultiLevelMenuOpen to true by default

**Comment by beli0135** [comment]
Hi Krekas. 
isMultiLevelMenuOpen when set to true does not open menu. I am wondering if I am making changes in right place. Not too good with JS.
Can you give me a push in a right direction how to solve this problem, as I really like it?
