### ISSUE TITLE
Request for intergrate with react

### ISSUE THREAD

**Issue by muhammadhamdani** [LaravelDaily/Larastarters#133]

**Comment by krekas** [comment]
@muhammadhamdani could you make a pr with **all** inertia themes?

**Comment by muhammadhamdani** [comment]
I'm confused using inertia themes

**Comment by PovilasKorop** [comment]
@muhammadhamdani sorry we're not planning react integrations at the moment.
As @krekas said we may accept it if someone makes a Pull Request.
