### ISSUE TITLE
Laravel Queue not working on laravel ui + Tabler

### ISSUE THREAD

**Issue by wausin** [LaravelDaily/Larastarters#145]
`
class User extends Authenticatable implements Auditable, MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable, AuditableTrait, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
        'user_type',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Send the queued email verification notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendEmailVerificationNotification()
    {
        $this->notify(new VerifyEmailQueued);
    }

    /**
     * Send the queued email reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordQueued($token));
    }
}`

i have added 2 new method at the bottom, but its still not trigger the queue.

**Comment by PovilasKorop** [comment]
@wausin sorry we don't support tabler anymore, removed it recently, because it jas too many bugs/changes.

Also, queue mechanism is not the part of starter kit that we generate, so we can't really help with it.
