### ISSUE TITLE
Windmill Issue

### ISSUE THREAD

**Issue by safeerbhatti** [LaravelDaily/Larastarters#19]
Hello i tried using your package but after installing windmill I'm facing this design which is not working at all
top bar is not working as well
![image](https://user-images.githubusercontent.com/16503882/140025241-61dea384-5368-48f5-9214-7b7a5110ca45.png)

**Comment by PovilasKorop** [comment]
@safeerbhatti have you run "npm install && npm run dev" and was it successful, with no errors?

**Comment by safeerbhatti** [comment]
yes it was successful and no errors

**Comment by PovilasKorop** [comment]
@safeerbhatti I've just released new `v0.2.1`, could you reinstall the package fresh and test if the issue is gone? Thank you!

**Comment by safeerbhatti** [comment]
Hi @PovilasKorop ... Reinstalled the package and issue is gone now.. thank you for awesome package! love your videos as well :D
