### ISSUE TITLE
shell_exec() has been disabled for security reasons

### ISSUE THREAD

**Issue by Gerardlc** [LaravelDaily/Larastarters#31]
Almost on every server "shell_exec" it's disabled.

this error is triggered here:

>  at vendor/laraveldaily/larastarters/src/Console/InstallCommand.php:58
>      54▕             );
>      55▕ 
>      56▕             // Install breeze
>      57▕             $this->requireComposerPackages('laravel/breeze:^1.4');
>   ➜  58▕             shell_exec('php artisan breeze:install');
>      59▕ 
>      60▕             file_put_contents(
>      61▕                 base_path('routes/web.php'),
>      62▕                 file_get_contents(__DIR__ . '/../../resources/stubs/routes.stub')

Any workaround?

**Comment by PovilasKorop** [comment]
@Gerardlc this package is not supposed to be run on the SERVER, it should be with `--dev` on your local machine.
