### ISSUE TITLE
npm run watch doesn't work.

### ISSUE THREAD

**Issue by erenergul** [LaravelDaily/Larastarters#32]
Hello , I bought a new mac. So i tried to start a project with your kit but i couldnt work with npm run watch. I thought because of macOS but I read comments on youtube videos. Some other people have same issue. I am using windmill theme with breeze. Can you please investigate about it. I tried poll as well. It doesnt updated after change. 

Thanks.

**Comment by PovilasKorop** [comment]
@erenergul we didn't configure this package to work seamlessly with `npm run watch`, our documentation says `npm run dev`.

That said, maybe we should configure it, so what is exactly the error you're getting?

**Comment by krekas** [comment]
`npm run watch` works fine for me with windmill specifically 
![image](https://user-images.githubusercontent.com/11015977/141684862-77f73219-2ecd-43e3-85cd-f75f0c61d5f8.png)

**Comment by erenergul** [comment]
I didnt get any error. It just doesn't compile after change. I dont know whats the issue.

**Comment by erenergul** [comment]
> `npm run watch` works fine for me with windmill specifically ![image](https://user-images.githubusercontent.com/11015977/141684862-77f73219-2ecd-43e3-85cd-f75f0c61d5f8.png)

Yes its same but did you try to change something and save ?

**Comment by krekas** [comment]
@erenergul what are you trying to change? Blade files doesn't need to compile.

**Comment by erenergul** [comment]
Oh thats why. Sorry my mistake. I thought livewire files needs to compile. Thats my mistake sorry.
