### ISSUE TITLE
replicated auth middleware in web.php

### ISSUE THREAD

**Issue by SunilYadav1961** [LaravelDaily/Larastarters#38]
`auth` middleware already used on group so don't need to use same middleware in that group. It dosen't make sense to use route middleware on `about` route.
In AdminLTE theme of Laravel UI (Bootstrap).
Reference :
![image](https://user-images.githubusercontent.com/72142357/141676453-709b2250-7270-4dd8-b9be-9979be69fd39.png)

**Comment by krekas** [comment]
@SunilYadav1961 feel free to make a PR :)

**Comment by SunilYadav1961** [comment]
> @SunilYadav1961 feel free to make a PR :)

@krekas Okay
This issue fixed in PR #39 so i think it should be close now.
