### ISSUE TITLE
reset password windmill  doesn't work

### ISSUE THREAD

**Issue by Desoleh** [LaravelDaily/Larastarters#43]
Hello , i tried to start a project using windmill theme with breeze. I have set my email in .env with mailtrap, but it didn't work to reset the password, Can you please investigate that reset password features.

Thanks.

<img width="799" alt="reset_password" src="https://user-images.githubusercontent.com/24294858/141878726-193f5d48-a753-4e9e-93e9-450022e564e0.png">

**Comment by PovilasKorop** [comment]
@Desoleh thanks for reporting, fixed
