### ISSUE TITLE
form does not cloes after div

### ISSUE THREAD

**Issue by pcmehrdad** [LaravelDaily/Larastarters#46]
Hi Mr @LaravelDaily 
here in :
https://github.com/LaravelDaily/Larastarters/blob/e6b26411040e72fcab42ba43cd36c4cf7c41d482/resources/stubs/ui/adminlte/views/auth/profile.blade.php#L93

`</form>` tag after `</div>` in line 93  is missed.
thanks

**Comment by krekas** [comment]
@pcmehrdad feel free to make pr :)

**Comment by pcmehrdad** [comment]
done!
https://github.com/LaravelDaily/Larastarters/pull/47
