### ISSUE TITLE
Suggestion to add laravel view components for each theme.

### ISSUE THREAD

**Issue by umefarooq** [LaravelDaily/Larastarters#49]
Hi, I really like these starter themes really easy to start your project admin. I have a suggestion to improve these themes more if we use Laravel view components for each theme. Let developer type or copy less html code just laravel components tags to make things more fast so there will be no html div break. we can have different components for each theme like 

1. sidebar or menu component
2. Bootstrap card component
3. Input fields components

Above are just basic components list we can add more and make development more fast. if any developer don't want to use these still they can use html.

Looking forward your comments regarding my suggestion.

**Comment by krekas** [comment]
Laravel/ui doesn't use blade components. Breeze does and themes use it. Of course those components could be improved so feel free to pr :)

**Comment by PovilasKorop** [comment]
@krekas I think that @umefarooq is suggesting exactly that - to add Blade components to bootstrap themes.

I'm not sure that many people would use that, but if you really think this feature would be useful please create a pull request with at least one theme covered with components, and then we could take over for other themes

**Comment by umefarooq** [comment]
Here is first look of volt login with component. I have created card component adding form in it. All these are using bootstrap. Here is my suggested component structure all bootstrap component in under component bootstrap directory (App\View\Components\BS) so these all themes can share them.

```
<x-bs.card>
 <x-slot name="header">
 Header
 </x-slot>
Here you can add text or html elements

 <x-slot name="footer">
 Footer
 </x-slot>
</x-bs.card>
```

or each theme has their own components?

<img width="999" alt="Screen Shot 2021-11-21 at 4 45 32 PM" src="https://user-images.githubusercontent.com/224341/142762539-93248f12-2560-4e1d-b649-33b1cfd0689d.png">

**Comment by krekas** [comment]
Themes can't have same components because of different styles

**Comment by PovilasKorop** [comment]
@umefarooq good start, but @krekas is right: the whole problem with components is that they would end up being different, in different themes.

We have this problem clearly in our quickadminpanel.com - that's why it's a very time-consuming work for us to add a new theme in that generator - that every new theme has its own structure, layout ideas, and the same components don't fit.

**Comment by umefarooq** [comment]
Yes these components should be theme specific. I was creating form input component everything was working fine but i was not showing validation error. after googling i found this cool package laravel forms components it support bootstrap 4 and 5, tailwind 1 and 2 frameworks easy to use. model binding create form with just component tags

https://github.com/protonemedia/laravel-form-components

Now need your suggestion should we use this or not? if we use this package than we have to create only theme specific components.

**Comment by PovilasKorop** [comment]
@umefarooq no no, we don't want any dependency on any other external packages.

That package looks cool, and I may review it on YouTube, but for larastarters, it should be only "native" components.

That said, if you agree that components are different for all themes, then what is the point of doing components at all? I always thought of larastarters as more or less unified codebase for all themes, and different components would break that idea, also adding more work to support those components in the future.

So, all in all, after some thinking, I will not accept this change into larastarters package. 

Closing the issue, and may reconsider if many people request it again and I feel that it's worth supporting.

**Comment by umefarooq** [comment]
Why should we reinvent a wheel again, We can use this package only for forms for all themes, other than that each theme can have separate set of UI components.

**Comment by PovilasKorop** [comment]
"there always somebody to take over package and keep rolling it"

>> Wrong, over my career I've seen dozens of packages abandoned which caused problems for their users

"why should i use this starter kit in my projects"

>> Because it's a STARTER kit, you use it only once and then can forget about it, even removing it from your vendor. You shouldn't care if Larastarters is upgraded, it's one-time use for new projects.

Generally, I understand your line of thought, it's just the approach that I'm not comfortable with, it's just too much work with those components, and no one else actually requested it. If I see bigger demand, then maybe I would rethink spending my time on this, otherwise, I have more important things to do.
