### ISSUE TITLE
improve HandleInertiaRequest Middleware

### ISSUE THREAD

**Issue by spawn81** [LaravelDaily/Larastarters#50]
Hi, first of all, thank you for this awesome package, it's very useful.
I noticed that in the share props of the Middleware,  all the user data field are passed. Thinking about the security, I guess that something like that could be very useful for the package:
```
 'auth' => [
                'user' => function () use ($request) {
                                       return $request->user() ? $request->user()->only(['email', 'name']) : null;

]
```
Hope it can be useful.
Cheers

**Comment by krekas** [comment]
@spawn81 it's laravel breeze code witch we are using. You can check their code here https://github.com/laravel/breeze/blob/1.x/stubs/inertia-common/app/Http/Middleware/HandleInertiaRequests.php#L38
