### ISSUE TITLE
Breeze with NotusJs css file size 44.8 mb.

### ISSUE THREAD

**Issue by manudev91** [LaravelDaily/Larastarters#52]
Hello @PovilasKorop, 
I used your Larastarters package with breeze and the NotusJS that I found, The CSS file is excessively huge, weighing up at 44.8 megabytes. Other methods I've tried have a maximum file size of 2 MB.

<img width="1057" alt="Screenshot 2021-12-10 at 7 09 44 AM" src="https://user-images.githubusercontent.com/94595455/145502831-ab61f580-cd95-490d-8a56-292131597fe1.png">

**Comment by krekas** [comment]
@manudev91 please enable tailwinds jit mode and check then
