### ISSUE TITLE
breeze with tailwindcomponents 404 on js/init-alpine.js

### ISSUE THREAD

**Issue by MatthiasHertel** [LaravelDaily/Larastarters#53]
https://github.com/LaravelDaily/Larastarters/blob/main/resources/stubs/breeze/tailwindcomponents/views/layouts/app.blade.php#L18

is it necessary here ?

**Comment by krekas** [comment]
@MatthiasHertel if I remember correctly after upgrading to alpinejs v3 yes it is necessary. Feel free to make pr :)
