### ISSUE TITLE
Password Authentication

### ISSUE THREAD

**Issue by seristee** [LaravelDaily/Larastarters#56]
I absolutely love your work and follow you on YouTube. My issue is when I create a new user on the registration page i get directed to the dashboard, however when i logout and try to log back in with the same password just created, it does not authenticate. I have to hash a password with Hash::make() then manually add it to the database for me to get authenticated.

**Comment by krekas** [comment]
Hi @seristee ,
Witch theme you are using? Authentication logic is done using breeze or UI. No controllers touched by this package

**Comment by seristee** [comment]
I'm using the Breeze/windmill theme.

**Comment by PovilasKorop** [comment]
@seristee we fail to reproduce the issue, can you maybe shoot a screencast, or some other step-by-step instructions on how to reproduce?

I've made a lot of demos based on Larastarters and it didn't fail for me in the way you're describing. Maybe you changed something in the code manually?

**Comment by seristee** [comment]
i created a fresh install and now it seem to work . Sorry for the trouble.
