### ISSUE TITLE
It's not a issue report

### ISSUE THREAD

**Issue by ArtMin96** [LaravelDaily/Larastarters#57]
```requireComposerPackages``` using this method I got the following problem: "The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly" and found the solution here [https://github.com/statamic/cms/issues/3383#issuecomment-846323885](https://github.com/statamic/cms/issues/3383#issuecomment-846323885) . Others may have the same problem. In order not to repeat that problem, I suggest adding this to the code.

From:

```php
(new Process($command, base_path(), ['COMPOSER_MEMORY_LIMIT' => '-1']))
             ->setTimeout(null)
             ->run(function ($type, $output) {
                 $this->output->write($output);
             });
```

To:

```php
(new Process($command, base_path(), ['HOME' => getenv ('HOME'), 'COMPOSER_MEMORY_LIMIT' => '-1']))
             ->setTimeout(null)
             ->run(function ($type, $output) {
                 $this->output->write($output);
             });
```

**Comment by PovilasKorop** [comment]
@ArtMin96 thank you for your comment, but since it's not a real issue, and it's not even our package problem, it's related to how composer works, I will close this issue on Github.
