### ISSUE TITLE
numbering of types to install

### ISSUE THREAD

**Issue by smokey18** [LaravelDaily/Larastarters#58]
![image](https://user-images.githubusercontent.com/22174467/147654708-6b2f30ff-97a3-40ab-b431-5f1b0d2ff8e3.png)

I've issue seen the numbering to choose from cmd while installing the package.
I'm using Git Bash in windows 10.
Can you help me with this matter?

**Comment by krekas** [comment]
@smokey18 package has nothing to do how you get output
