### ISSUE TITLE
@endforeach here is after </tbody>, but the foreach-loop should end inside the <tbody></tbody> tag.

### ISSUE THREAD

**Issue by JafTan21** [LaravelDaily/Larastarters#59]
https://github.com/LaravelDaily/Larastarters/blob/2fc9419572d1a1c6b024d41d898ce8dadc9357e4/resources/stubs/breeze/notusjs/views/users/index.blade.php#L44

**Comment by krekas** [comment]
@JafTan21 feel free to make pr with the fix :)
