### ISSUE TITLE
Changes to tailwind css v.3.0

### ISSUE THREAD

**Issue by Kmap-Holdings** [LaravelDaily/Larastarters#65]
Good day, 

Are you going to make the changes to your starter kits to ensure that they are compliant with Tailwind CSS v3.0. To be specific the purge/content options. I would do it for you, but I have no clue how to contribute in this environment yet. I will make time to find out in the near future. Thanks.

**Comment by PovilasKorop** [comment]
@Kmap-Holdings hi, we generate the code based on THEMES that are open-source, we haven't actually created them. And they are all based on Tailwind v2, last time I checked.

Maybe in the future, as Tailwind 3 grows in usage, we will change the themes or maybe change something in the way how we compile everything, but for now it's not in plans.

**Comment by Kmap-Holdings** [comment]
Good day. Thanks for the response. Duly noted. Is not really a big issue,
and was wondering if new users to you channel will be put off by it. I'm
already hooked so I'm not going anywhere. Thanks for your time. Keep well
