### ISSUE TITLE
Upgrading coreui.bundle.min.js to 4.0.5 version or higher

### ISSUE THREAD

**Issue by dickygiancini** [LaravelDaily/Larastarters#67]
Good Day!

I am wondering if the coreui option on Laravel UI can be upgraded to 4.0.5 or higher since it has multiple errors on some libraries, especially on jQuery ( reference : [https://github.com/coreui/coreui-free-bootstrap-admin-template/issues/578](url) ), it shows below error :

`Uncaught TypeError: Cannot set property 'Constructor' of undefined
    at index.js:234
    at index.js:214
    at Array.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (index.js:214)`
    
Thank you for the useful package!

**Comment by PovilasKorop** [comment]
@dickygiancini currently we're busy with other projects, could you submit a pull request for this change?

**Comment by dickygiancini** [comment]
@PovilasKorop THank you for the reply! I've sent the Pull Request as you suggest to upgrading coreui.bundle.min.js to 4.0.5

**Comment by PovilasKorop** [comment]
@dickygiancini thanks, I've made the release: https://github.com/LaravelDaily/Larastarters/releases/tag/1.4.1
