### ISSUE TITLE
npm install && npm run dev issue 

### ISSUE THREAD

**Issue by vineetchuahan15** [LaravelDaily/Larastarters#7]
**While running npm install && npm run dev error occured as:**

- npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: tailwindcss@2.2.19
npm ERR! node_modules/tailwindcss
npm ERR!   dev tailwindcss@"^2.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@"^1.4.6" from tailwindcss-multi-theme@1.0.4
npm ERR! node_modules/tailwindcss-multi-theme
npm ERR!   dev tailwindcss-multi-theme@"^1.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by krekas** [comment]
Which theme are you trying to use? How does your package.json file look?

**Comment by vineetchuahan15** [comment]
> Which theme are you trying to use? How does your package.json file look?
I am using windmill theme

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "@tailwindcss/forms": "^0.2.1",
        "alpinejs": "^2.7.3",
        "autoprefixer": "^10.1.0",
        "axios": "^0.21",
        "color": "^4.0.1",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.2.1",
        "postcss-import": "^12.0.1",
        "tailwindcss": "^2.0.2",
        "tailwindcss-multi-theme": "^1.0.4"
    }
}
```

**Comment by JakyeRU** [comment]
I can confirm having this issue as well. A workaround that worked for me is running `npm install --force`.

**Comment by PovilasKorop** [comment]
@vineetchuahan15 @JakyeRU thanks for reporting, we're fixing it in v0.2, by removing Windmill dark theme. Release coming soon, this week.

**Comment by vineetchuahan15** [comment]
Thanks sir

**Comment by PovilasKorop** [comment]
@vineetchuahan15 @JakyeRU I've just released the v0.2, can you try to reinstall the package again from scratch in a new Laravel project and confirm that the issue is gone?

**Comment by JakyeRU** [comment]
I can confirm that the issue is gone.

**Comment by PovilasKorop** [comment]
@JakyeRU great thanks
