### ISSUE TITLE
dropdown don't work 

### ISSUE THREAD

**Issue by Sourovahmad** [LaravelDaily/Larastarters#74]
![image](https://user-images.githubusercontent.com/64475548/168456101-848704e7-b7ef-48ab-9232-d14c41a6abd5.png)
those dropdown don't work on Bootstrap -> PlainAdmin

**Comment by krekas** [comment]
@Sourovahmad in bootstrap.js file remove this line
```js
window.$ = window.jQuery = require('jquery');
```
and after recompile should work.

**Comment by Sourovahmad** [comment]
It's worked. thanks
