### ISSUE TITLE
Tailwind CSS issue

### ISSUE THREAD

**Issue by rabol** [LaravelDaily/Larastarters#77]
When installing larastartes on a new Laravel 9 project and select Windmill one get the following warning when running:

```
npm run dev
```

warn - The `purge`/`content` options have changed in Tailwind CSS v3.0.
warn - Update your configuration file to eliminate this warning.
warn - https://tailwindcss.com/docs/upgrade-guide#configure-content-sources

**Comment by krekas** [comment]
@rabol these layouts isn't made with for v3. Feel free to make pr
