### ISSUE TITLE
ErrorException while initiating the command: php artisan larastarters:install

### ISSUE THREAD

**Issue by smartnathan** [LaravelDaily/Larastarters#86]
This error was encountered on a fresh Laravel 8 installation.

`ErrorException 

  Undefined property: LaravelDaily\Larastarters\Console\InstallCommand::$components

  at vendor/laraveldaily/larastarters/src/Console/InstallCommand.php:53
     49▕     public function handle()
     50▕     {
     51▕         $this->php_version = $this->option('php_version');
     52▕         
  ➜  53▕         $kit = $this->components->choice(
     54▕             'Which Laravel starter kit you want to use?',
     55▕             ['Laravel Breeze (Tailwind)', 'Laravel Breeze & Inertia (Tailwind)', 'Laravel UI (Bootstrap)'],
     56▕             0
     57▕         );

      +14 vendor frames 
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))`

**Comment by PovilasKorop** [comment]
@smartnathan this package wouldn't work with Laravel 8, because it's adopted the latest Laravel 9 changes with Vite server.

Good point, I need to add it to Readme instructions.
