### ISSUE TITLE
Error in tailwind components dashboard files

### ISSUE THREAD

**Issue by ahmedmuhammady30** [LaravelDaily/Larastarters#89]
There is some errors in Tailwind Components dashboard files which are not found how to solve this ?

**Comment by krekas** [comment]
@ahmedmuhammady30 what error? What files? Be more specific

**Comment by ahmedmuhammady30** [comment]
Tailwind components dashboard appears like no css or js files are loaded , It is rendered like a default no styled html page

**Comment by PovilasKorop** [comment]
@ahmedmuhammady30 not sure, just tried, works for me, see attached: 
<img width="857" alt="Screenshot 2022-09-20 at 07 00 35" src="https://user-images.githubusercontent.com/1510147/191164628-2f0d3406-486a-4888-873a-53e12c72195e.png">

Maybe you haven't run `npm run dev` or it failed for you?
