### ISSUE TITLE
Stubs out of date

### ISSUE THREAD

**Issue by Trolli07** [LaravelDaily/Larastarters#90]
Hello,

The stubs need to be updated, because of this commit :
- https://github.com/laravel/breeze/commit/dc3564d69d103ca8de29754022c0b74fa17602fc

Some other stubs are not up to date too :
- https://github.com/laravel/breeze/commit/da030d58ddefb1d35ee08e70af6dda3793613eb4
- ...

Olivier

**Comment by krekas** [comment]
Hi @Trolli07,
Can you update?

**Comment by PovilasKorop** [comment]
@Trolli07 can you fix with a Pull Request?

**Comment by PovilasKorop** [comment]
@Trolli07 fixed with the new release of `v2.1.0`, please update
